name: Terraform Plan
on:
  push:
    branches:
      - main

permissions:
  id-token: write    # Allow the workflow to request an OIDC token
  contents: read     # Allow the workflow to read repository code

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials                  # Handles AWS login using OIDC and the specified role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: terraform/live/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/live/dev
        run: terraform validate
      
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/live/dev
          framework: terraform
          quiet: true
          skip_check: CKV_AWS_144,CKV2_AWS_62,CKV2_AWS_64

      - name: Terraform Plan
        run: terraform plan